name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Penilaian Otomatis ALU
      id: penilaian-otomatis-alu
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Penilaian Otomatis ALU
        setup-command: ''
        command: echo "Penilaian dijalankan via GitHub Actions. Lihat tab 'Actions'
          untuk hasil detail."
        timeout: 1
        max-score: 100
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        PENILAIAN-OTOMATIS-ALU_RESULTS: "${{steps.penilaian-otomatis-alu.outputs.result}}"
      with:
        runners: penilaian-otomatis-alu
